version: '3.7'

services:
  postgres:
    container_name: seed_postgres
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    logging:
      driver: none
    ports:
      - 5432:5432

  django:
    container_name: seed_django
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      PROCESS: DEV_DJANGO
      test: "pytest -v --cov . --cov-report term-missing
      --cov-fail-under=100 --flake8 --no-migrations
      --reuse-db"
