version: '3.7'

services:
  postgres:
    container_name: seed_postgres
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    logging:
      driver: none

  rabbitmq:
    container_name: seed_rabbitmq
    image: rabbitmq:3.8.9-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    logging:
      driver: none

  redis:
    container_name: seed_redis
    image: redis:6.0.9-alpine3.12
    logging:
      driver: none

  django:
    container_name: seed_django
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      PROCESS: DEV_DJANGO
      test: "pytest -v --cov . --cov-report term-missing
      --cov-fail-under=100 --flake8 --mypy -n 4 --no-migrations
      --reuse-db
      -W ignore::django.utils.deprecation.RemovedInDjango40Warning"
      makemigrations: python manage.py makemigrations
      migrate: python manage.py migrate
      makemessages: python manage.py makemessages
      compilemessages: python manage.py compilemessages
      outdated: pip list --outdated --format=columns
      bandit: bandit -r .
      safety: safety check
      mypy: mypy .
      flake8: flake8 .
      check: python manage.py check --deploy
      shell: python manage.py shell_plus

  celery:
    container_name: seed_celery
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PROCESS: DEV_CELERY
