# Generated by Django 3.1.4 on 2022-08-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='id',
        ),
        migrations.AddField(
            model_name='airplane',
            name='plane_id',
            field=models.IntegerField(default=10, primary_key=True, serialize=False),
        ),
    ]
